Web_biz_app/web_biz_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'photos#index'
  resources  :users, only: [:show, :edit, :update, :index]
  resources  :tags, param: :name,  only: [:index, :show]
  resources  :photos do
    resources :likes,    only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  scope module: :photos do
    resources :popular, only: :index
  end
end

Web_biz_app/web_biz_app/app/models/photo.rb
# coding: utf-8
class Photo < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  has_many   :comments,         dependent: :destroy
  has_many   :likes,            dependent: :destroy
  has_many   :photo_images, dependent: :destroy
  has_one    :main, class_name: "PhotoImage"
  accepts_nested_attributes_for :photo_images, allow_destroy: true, reject_if: :all_blank
  validates  :catch_copy, :concept, :title,  presence: true

  paginates_per 8

  SUB_CONTENT_MAX = 2
  def set_sub_contents
    sub_contents = photo_images.sub
    SUB_CONTENT_MAX.times { |i| sub_contents[i] ||= photo_images.build(role: "sub") }
    sub_contents
  end

  def like_user(user)
   likes.find_by(user_id: user)
  end

  def self.search(keyword)
    photo_ids = [] # 検索でヒットしたユーザーのidを格納する配列
    
    #入力がある場合とない場合で分ける
    if keyword.presence
    #入力文字列を空白で区切ってリストに格納
      patterns = keyword.split(/[ , ]/)
      sql_body = ''
      tagged_photos = []

      #SQL文を作成する
      patterns.each do |pattern|
        sql_body += ' and ' unless sql_body.blank?
        sql_body += " concat(title, concept) like '%#{pattern}%' "
        tagged_photos.push(Photo.tagged_with(pattern)) # "pattern"というタグを持つPhotoのリストがpushされる
      end
      sql = "select * from photos where #{sql_body} order by id desc"
    
    #find_by_sqlで条件を満たすユーザーを取得し、それらのidを取得する
      photo_ids << Photo.find_by_sql(sql).map(&:id)

      # リストをidに変換
      tagged_photos.each do |photo|
        photo_ids << photo.ids
      end

      photo_ids.flatten!
      where(:id => photo_ids)
    else
      Photo.all
    end
  end    
end

Web_biz_app/web_biz_app/app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.search(params[:keyword]).order("photos.created_at DESC").eager_load(:user, :photo_images).page(params[:page])
    @status = 'newest'
  end

  def new
    @photo        = Photo.new
    @main_content = @photo.photo_images.build
    @sub_contents = 1.times { @photo.photo_images.build }
  end

  def create
    @photo  = current_user.photos.new(create_params)

    if @photo.save
      redirect_to root_path, notice: 'Posted Successfully!'
    else
      render :new, alert: 'Sorry, but something went wrong.'
    end
  end

  def show
    @likes    = Like.where(photo_id: params[:id])
    @comments = @photo.comments.includes(:user).all
    @comment  = @photo.comments.build(user_id: current_user.id) if current_user
  end

  def edit
    @main_content = @photo.photo_images.main
    @sub_contents = @photo.set_sub_contents
  end

  def update
      if @photo.user_id == current_user.id && @photo.update(create_params)
        redirect_to root_path, notice: 'Updated Successfully!'
      else
        render :edit, alert: 'Sorry, but something went wrong.'
      end
  end

  def destroy
    @photo.destroy
    redirect_to root_path, notice: 'Deleted Successfully!'
  end

  private

  def set_photo
    @photo    = Photo.find(params[:id])
  end

  def create_params
    params.require(:photo).permit(
      :title,
      :catch_copy,
      :concept,
      photo_images_attributes: [:id, :content, :role]
      ).merge(tag_list: params[:photo][:tag])
  end

end

Web_biz_app/web_biz_app/app/helpers/photos_helper.rb
module PhotosHelper
  def likes_counter(likes)
    likes.count
  end
end

Web_biz_app/web_biz_app/app/views/photos/_form.html.haml
.container.proto-new
  = form_for @photo do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, class: "proto-new-title", placeholder: "Title"
      .row
        .col-md-12
          .cover-image-upload.js-preview-images
            = f.fields_for :photo_images, @main_content do |photo_image|
              = photo_image.file_field :content
              = photo_image.hidden_field :role, value: :main
        .col-md-12
          %ul.proto-sub-list.list-group
            = f.fields_for :photo_images, @sub_contents do |photo_image|
              %li.list-group-item.col-md-4
                .image-upload.js-preview-images
                  = photo_image.file_field :content
                  = photo_image.hidden_field :role, value: :sub
            %li.list-group-item.col-md-4
              .image-upload-plus
                %span +
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, cols:"30", rows: "4", placeholder: "Concept"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = text_field_tag "photo[tag][]", "", placeholder: "Web Design",maxlength: 9
            .col-md-3
              = text_field_tag "photo[tag][]", "", placeholder: "UI",maxlength: 9
            .col-md-3
              = text_field_tag "photo[tag][]", "", placeholder: "Application",maxlength: 9
      .row.text-center.proto-btn
        = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

Web_biz_app/web_biz_app/app/views/photos/_photo.html.haml
.col-sm-12.col-md-6.proto-content
  .thumbnail
    = link_to photo_path(photo) do
      = image_tag photo.photo_images.main.first.content
    - if user_signed_in? && current_user.id == photo.user_id
      .dropdown.drop_menu_location
        %button.btn.btn-default.dropdown-toggle{ id: "dropdownMenu", type: "button",  data: { toggle: "dropdown" } } Action
        %ul.dropdown-menu{ aria: { labelledby: "dropdownMenu1" } }
          %li
            = link_to "Delete", photo, method: :delete
          %li
            = link_to "Edit"  , edit_photo_path(photo)
    .caption
      %h3= photo.title
      .proto-meta
        .proto-user
          = link_to "by #{ photo.user.username }", user_path(photo.user)
        .proto-posted
          = photo.created_at.strftime("%b %d")
      %ul.proto-tag-list.list-inline
        = render partial: "tags/button_template", collection: photo.tags, as: "tag"

Web_biz_app/web_biz_app/app/views/photos/edit.html.haml
= render partial: "form"

Web_biz_app/web_biz_app/app/views/photos/index.html.haml
= render partial: "layouts/top_content"
.container.proto-list
  .row
    = render partial: "photos/photo", collection: @photos

.text-center
  %ul.pagination
    %li.disabled
      = paginate(@photos)

Web_biz_app/web_biz_app/app/views/photos/new.html.haml
%form.container.proto-new{action: ""}
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %input.proto-new-title{type: "text", placeholder: "Title"}/
    .row
      .col-md-12
        .cover-image-upload
          %input{type: "file"}/
      .col-md-12
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload
              %input{type: "file"}/
          %li.list-group-item.col-md-4
            .image-upload
              %input{type: "file"}/
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        %input{type: "text", placeholder: "Catch Copy"}/
      .col-md-12
        %textarea{name: "", cols: "30", rows: "4", placeholder: "Concept"}
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            %input{type: "text", placeholder: "Web Design"}/
          .col-md-3
            %input{type: "text", placeholder: "UI"}/
          .col-md-3
            %input{type: "text", placeholder: "Application"}/
    .row.text-center.proto-btn
      %button.btn.btn-lg.btn-primary.btn-block{type: "submit"} Publish

Web_biz_app/web_biz_app/app/views/photos/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to image_tag(@photo.user.avatar, size: "64x64", class: "media-object"), user_path(@photo.user)
        .media-body
          %h4#top-aligned-media.media-heading
            = @photo.title
          .proto-user
            = link_to "by #{ @photo.user.username }", user_path(@photo.user)
            %span.degree= @photo.user.profile

    .col-md-6.text-right
      #like-buttons
        = render partial: "likes/like"
  .row
    .col-md-9
      = image_tag("#{ @photo.photo_images.main.first.content }", class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        - @photo.photo_images.sub.each do |sub_content|
          %li.list-group-item
            = image_tag(sub_content.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p= @photo.catch_copy
    .col-md-6
      %h4 Concept
      %p= @photo.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        = render partial: "tags/button_template", collection: @photo.tags, as: "tag"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num#js-comments-counter
        = "(#{ @photo.comments.count })"
  .col-md-8
    #js-comments
      = render partial: "comments/comment", collection: @comments
    %form.form-inline
    - if user_signed_in?
      = form_for [@photo, @comment], remote: true do |f|
        = f.hidden_field :user_id, value: current_user.id
        = f.hidden_field :prototype_id, value: @photo.id
        %h4 Write a comment
        .row
          .form-group.col-md-10
            = f.text_area :content, require: true, rows: "3", placeholder: "Your comments",id: "comment_content", class: "form-control"

          .form-group.col-md-2
            = f.submit "Comment", class: "button btn btn-primary"