Web_biz_app/web_biz_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'photos#index'
  resources  :users, only: [:show, :edit, :update, :index]
  resources  :tags, param: :name,  only: [:index, :show]
  resources  :photos do
    resources :likes,    only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  scope module: :photos do
    resources :popular, only: :index
  end
end

Web_biz_app/web_biz_app/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :photo, counter_cache: :likes_count
end

Web_biz_app/web_biz_app/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_photo, :set_likes, only: [:create, :destroy]

  def create
    @like  = Like.create(user_id: current_user.id, photo_id: params[:photo_id])
    render_js
  end

  def destroy
    @like = current_user.likes.find_by(photo_id: params[:photo_id])
    @like.destroy
    render_js
  end

  private

  def set_photo
    @photo = Photo.find(params[:photo_id])
  end

  def set_likes
    @likes = Like.where(photo_id: params[:photo_id])
  end

  def render_js
   render partial: "likes/js_like"
  end
end

Web_biz_app/web_biz_app/app/helpers/likes_helper.rb
module LikesHelper
end

Web_biz_app/web_biz_app/app/views/likes/_js_like.js.haml
$("#like-buttons").html("#{ j(render partial: 'like') }");

Web_biz_app/web_biz_app/app/views/likes/_like.html.haml
- if user_signed_in?
  - if @photo.like_user(current_user.id)
    = button_to photo_like_path(id: @photo.like_user(current_user), user_id: current_user, photo_id: @photo.id), method: :delete, class: "btn btn-default", remote: true do
      = image_tag("icon_heart_red.svg")
      LIKE
      %span.num
      = likes_counter(@likes)
  - else
    = button_to photo_likes_path(@photo), class: "btn btn-default", remote: true do
      = image_tag("icon_heart.svg")
      LIKE
      %span.num
      = likes_counter(@likes)
- else
  = button_to new_user_session_path, class: "btn btn-default" do
    = image_tag("icon_heart.svg")
    Like
    %span.num
      = likes_counter(@likes)