Web_biz_app/web_biz_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'photos#index'
  resources  :users, only: [:show, :edit, :update, :index]
  resources  :tags, param: :name,  only: [:index, :show]
  resources  :photos do
    resources :likes,    only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  scope module: :photos do
    resources :popular, only: :index
  end
end

Web_biz_app/web_biz_app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

Web_biz_app/web_biz_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_photo, only: [:create, :destroy]

  def create
    @comment  = @photo.comments.create(create_comment_params)
    @comments = @photo.comments
    render_js
  end

  def destroy
    Comment.find(params[:id]).destroy
    @comments = @photo.comments
    render_js
  end

  private

  def set_photo
    @photo = Photo.find(params[:photo_id])
  end

  def create_comment_params
    params.require(:comment).permit(:user_id, :photo_id, :content)
  end

  def render_js
    render partial: "comments/js_comment"
  end
end

Web_biz_app/web_biz_app/app/helpers/comments_helper.rb
module CommentsHelper
end

Web_biz_app/web_biz_app/app/views/comments/_comment.html.haml
.media
  .media-left
    = link_to image_tag(comment.user.avatar, size: "64x64", class: "media-object", style: "width: 64px; height: 64px;" ), user_path(@photo.user)
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.username
      - if comment.user_id == current_user.id
        = link_to "Delete", photo_comment_path(comment, photo_id: comment.photo.id), method: :delete, class: "btn btn-xs navbar-inverse btn-delete", remote: true
      %a.anchorjs-link{ href: "#top-aligned-media" }
        %span.anchorjs-icon
    %p
    = comment.content

Web_biz_app/web_biz_app/app/views/comments/_js_comment.js.haml
$("#comment_content").val("");
$("#js-comments-counter").text("(#{ @photo.comments.count })");
$("#js-comments").html("#{ j(render partial: 'comment', collection: @comments) }");