Web_biz_app/web_biz_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'photos#index'
  resources  :users, only: [:show, :edit, :update, :index]
  resources  :tags, param: :name,  only: [:index, :show]
  resources  :photos do
    resources :likes,    only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  scope module: :photos do
    resources :popular, only: :index
  end
end

Web_biz_app/web_biz_app/app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; CAMON 2017.
  

Web_biz_app/web_biz_app/app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo_top.jpg", alt: "CAMON -CONNECT CAMERAMAN WITH MODEL", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li
            = form_tag root_path, method: "get", class: "navbar-form" do
              .input-group
                = text_field_tag :keyword, nil, class: "form-control"
                %span.input-group-btn
                  = button_tag type: "submit", class: "btn btn-default", name: nil do
                    = content_tag :span, "", class: "glyphicon glyphicon-camera"
          %li
            = link_to users_path do
              %i.glyphicon.glyphicon-user
          %li.dropdown
            %a.dropdown-toggle{ aria: { expanded: false }, data: { toggle: "dropdown" }, href: "#", role: "button" }
              = current_user.username
              %span.caret
            %ul.dropdown-menu{ role: "menu" }
              %li
                = link_to "My Page", user_path(current_user)
              %li
                = link_to "Profile Edit", edit_user_path(current_user)
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to "New Photo", new_photo_path
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to "Get Started", user_session_path

Web_biz_app/web_biz_app/app/views/layouts/_top_content.html.haml
.jumbotron
  .container.text-center
    = image_tag("", alt: "", height: "0px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{ class: "#{ "active" if @status == 'popular' }" }
          = link_to "Popular PROTO", popular_index_path
        %li{ class: "#{ "active" if @status == 'newest' }" }
          = link_to "Newest PROTO", root_path
      = link_to 'View Tags',tags_path, class: "btn btn-default col-lg-1"

Web_biz_app/web_biz_app/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Photo Match
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"